# Site settings
title: MNMistry
email: manismistry@live.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Web-designer, programmer, animator.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Talon_HQ
github_username:  Net-Slayer
exclude: [
.git,
.gitignore,
.DS_Store,
CNAME,
svg,
scss,
.sass-cache,
package.json,
Gruntfile.js,
node_modules,
readme.md,
templates,
Source,
htmtmp,
js/global,
js/total,
js/libs,
images/global,
release/css/global,
release/css/total,
]

# Build settings
markdown: kramdown
