# Site settings
title: MNMistry
email: manismistry@live.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Web-designer, programmer, animator.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
exclude: [
.git,
.gitignore,
.DS_Store,
CNAME,
svg,
scss,
.sass-cache,
package.json,
Gruntfile.js,
node_modules,
readme.md
]

# Build settings
markdown: kramdown
